### PR TITLE
Add links to code examples

### PR DESCRIPTION
**Pull request by karlbaker02**
### Context

This commit adds links to the relevant data structures in the output for the various examples. This is intended to make it easier for users to navigate between the result of a method call and how they can interrogate that result to get the data they need.

### Changes proposed in this pull request

Add links to code examples.

### Guidance to review

Check links work.

### CODE REVIEW

**Comment by bahmady** [comment]
Echo what Gideon said, but also hasn't Seamus already started testing and is continuing?

**Comment by karlbaker02** [comment]
@bahmady Yes he has started and is continuing. To be honest I more wanted to see what the feedback was from this PR. There have been a number of users getting lost in the research to reaching the object that they're getting back and then jumping around the documentation aimlessly, so I was somewhat hoping that we could address that - probably after the research concludes.

@gidsg :(

**Comment by bahmady** [comment]
@karlbaker02 I've nothing against the changes in principle, though I don't think there's a way around the shortcoming @gidsg has pointed out, in GitHub — and I would advise against making any changes live whilst Seamus is still researching it in one state. 

Since we're likely to change the way user journeys lead to this information so much, I think in the long run it will be more useful to use the feedback we get from Seamus and Emma when we end up making wholesale changes.

**Comment by SeamusAKeating** [comment]
@karlbaker02, @bahmady; I think this is a good idea, it seems like a significant enough change and would be better tested with the other design, content changes that will result from this round of research. I reckon that the client library will require a further round of research.

**Pull request closed without merging**
